# Generated by Django 6.0 on 2026-01-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitcompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitcompletion',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit'),
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
    ]
