# Generated by Django 6.0 on 2026-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habitcompletion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='weight',
            field=models.PositiveIntegerField(help_text='1 (low) to 5 (high)'),
        ),
    ]
