# Generated by Django 4.2 on 2026-01-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_difficulty_alter_habit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='momentum',
            field=models.FloatField(default=0.0),
        ),
    ]
